services:
  web:
    build: .
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      AWS_ACCESS_KEY_ID: AKIsomething
      AWS_SECRET_ACCESS_KEY: GolOsomething
      AWS_DEFAULT_REGION: us-east-1
      COGNITO_APP_CLIENT_ID: 2v0henecrkp0b6i4o4t6ougm8h
      COGNITO_USER_POOL_ID: us-east-1_n4uOV2f8m
