apiVersion: apps/v1
kind: Deployment
metadata:
  name: cognito-go-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cognito-go-app
  template:
    metadata:
      labels:
        app: cognito-go-app
    spec:
      containers:
        - name: cognito-go-app
          image: video-auth:latest
          ports:
            - containerPort: 8080
          env:
            - name: CLIENT_ID
              value: "16j9h9kmmlregfdcqr0fqldv6u"
            - name: CLIENT_SECRET
              value: "la42qrepmo3ja48cb98pjaqn8eojf1jgj0jjleqdugh52nrq76e"
            - name: REDIRECT_URL
              value: "https://d84l1y8p4kdic.cloudfront.net"
            - name: ISSUER_URL
              value: "https://cognito-idp.us-east-1.amazonaws.com/us-east-1_zECx5gApz"
