apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: video-auth
  template:
    metadata:
      labels:
        app: video-auth
    spec:
      containers:
        - name: video-auth
          image: video-auth:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: cognito-secrets
                  key: cognito-client-id
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: cognito-secrets
                  key: cognito-client-secret
            - name: REDIRECT_URL
              valueFrom:
                secretKeyRef:
                  name: cognito-secrets
                  key: cognito-redirect-url
            - name: ISSUER_URL
              valueFrom:
                secretKeyRef:
                  name: cognito-secrets
                  key: cognito-issuer-url