apiVersion: v1
kind: Secret
metadata:
  name: aws-secrets
type: Opaque
data:
  AWS_REGION: dXMtZWFzdC0x
  COGNITO_USER_POOL_ID: dXMtZWFzdC0xX240dU9WMmY4bQ==
  COGNITO_CLIENT_ID: MnYwaGVuZWNya3AwYjZpNG80dDZvdWdtOGg=
  COGNITO_CLIENT_SECRET: aWlnN2s4Y2ZpOG5yZmxkMmhqM2RkbWRsOG5rMjF1anA2dTExNnBxcDNtN2tvN3RybTBo
