apiVersion: v1
kind: Service
metadata:
  name: video-auth
spec:
  selector:
    app: video-auth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer # ou LoadBalancer se você precisar de acesso externo diretamente
