apiVersion: v1
kind: Service
metadata:
  name: cognito-go-app
spec:
  selector:
    app: cognito-go-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer # ou LoadBalancer se você precisar de acesso externo diretamente
