name: Deploy to AWS

on:
  push:
    branches:
      - main
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_SESSION_TOKEN:
        required: true
      AWS_REGION_DEFAULT:
        required: true
      AWS_ACCOUNT_ID:
        required: true
      CLUSTER_NAME:
        required: true
      COGNITO_CLIENT_ID:
        required: true
      COGNITO_CLIENT_USER_POOL_ID:
        required: true
      COGNITO_CLIENT_SECRET:
        required: true
      COGNITO_REDIRECT_URL:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION_DEFAULT }}

      - name: Create ECR repository
        run: |
          aws ecr describe-repositories --repository-names video-auth || aws ecr create-repository --repository-name video-auth

      - name: Build Docker image
        run: docker build -t video-auth:latest .

      - name: Push Docker image to ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION_DEFAULT }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION_DEFAULT }}.amazonaws.com
          docker tag video-auth:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION_DEFAULT }}.amazonaws.com/video-auth:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION_DEFAULT }}.amazonaws.com/video-auth:latest

      - name: Deploy to EKS
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        run: |
          aws eks update-kubeconfig --name ${{ secrets.CLUSTER_NAME }} --region ${{ secrets.AWS_REGION_DEFAULT }}
          kubectl create secret generic cognito-secrets \
            --from-literal=cognito-client-id=${{ secrets.COGNITO_CLIENT_ID }} \
            --from-literal=cognito-client-secret=${{ secrets.COGNITO_CLIENT_SECRET }} \
            --from-literal=cognito-redirect-url=${{ secrets.COGNITO_REDIRECT_URL }} \
            --from-literal=cognito-issuer-url=https://cognito-idp.${{ secrets.AWS_REGION_DEFAULT }}.amazonaws.com/${{ secrets.COGNITO_CLIENT_USER_POOL_ID }} --dry-run=client -o yaml | kubectl apply -f -
          envsubst < infra/deployment.yaml | kubectl apply -f -
          kubectl apply -f infra/service.yaml
          kubectl set image deployment/video-auth video-auth=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION_DEFAULT }}.amazonaws.com/video-auth:latest
